### ISSUE TITLE
Error handling for rmot_assign_data

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/hmde#8]
rmot_assign_data(mtcars) this is bad

 #TODO: Check names are in model_template
abort if not model template

**Comment by fontikar** [comment]
4 years out of date but still a good resource: 
- https://bookdown.org/rdpeng/RProgDA/error-handling-and-generation.html

 For tidyverse like error messages: 
 - https://style.tidyverse.org/error-messages.html 
 
 {galah-R} the package has some specific .R file containing the functions that checks the inputs of their functions
-  https://github.com/AtlasOfLivingAustralia/galah-R/blob/35975795cbf67aa4d543972545859a49b0295c64/R/check.R

**Comment by Tess-LaCoil** [comment]
To do:
- Change error handling to use stop() properly
- Have checks on data types as well as size structures
- Standardise error feedback and get a second pair of eyes on what error messages say.

**Comment by Tess-LaCoil** [comment]
Finalised testing for assign_data function:
https://github.com/traitecoevo/hmde/commit/ef660c1e3df48a2f3a2ca21dff40a6e9211054ce
